In [1]:
import pandas as pd
import numpy as np

In [2]:
a=[1,2,'3']

b=np.array(a,dtype=float)

b

array([1., 2., 3.])

In [3]:
c=np.ones(6,dtype=float)
c

array([1., 1., 1., 1., 1., 1.])

In [4]:
d=np.zeros((3,6),dtype=int)
d

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [5]:
e=np.full(6,8)
e

array([8, 8, 8, 8, 8, 8])

In [6]:
a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
b=np.linspace(1,10,6,dtype=int)
b

array([ 1,  2,  4,  6,  8, 10])

In [8]:
b=np.identity(5) # n*n matrix
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
c=np.eye(3,4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [10]:
d=np.random.rand(3) # size betw 0 and 1 
d

array([0.19266312, 0.91270385, 0.19924851])

In [11]:
e=np.random.randint(12,20,6) # start,end,step
e

array([13, 14, 17, 19, 13, 15])

In [12]:
a=np.array([i for i in range(12)])
print(a.dtype) # data type
print(a.strides) # strides gives u the no of bytes req to reach the next element
print(a.shape) #shape of the array
print(a.data) # reference to the first element

int32
(4,)
(12,)


In [13]:
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)

a+b

array([23, 10, 25, 13, 24])

In [14]:
print(a)
print(a.argmin())
print(a.max())
print(a.argmax())
print(a.sum())

[ 6  7 15  9  9]
0
15
2
46


### Boolean Indexing

In [15]:
a=np.random.randint(1,20,6)
a

array([12, 16, 19,  9, 18,  1])

In [16]:
# extarct elements having value>10

print(a>10)

[ True  True  True False  True False]


In [17]:
a[a>10]

array([12, 16, 19, 18])

In [18]:
a[(a>10) & (a<=15)]

array([12])

In [23]:
print(a)
ind=np.where(b>1)
a[ind]

[12 16 19  9 18  1]


array([16, 19,  9, 18])

### Multi dimentional numpy arr

In [26]:
a=np.random.randint(1,20,(3,4))
a

array([[17, 16, 11, 15],
       [ 5,  3,  1, 11],
       [10,  9, 11, 12]])

In [27]:
a[a>10]=32
a

array([[32, 32, 32, 32],
       [ 5,  3,  1, 32],
       [10,  9, 32, 32]])

In [36]:
bool_arr=a[:,2]==32
print(bool_arr)

a[bool_arr,2]=23
a

[ True False  True]


array([[32, 32, 23, 32],
       [ 5,  3,  1, 32],
       [10,  9, 23, 32]])

### Broadcasting

In [56]:
a=np.random.randint(1,20,(4,3))
b=np.random.randint(20,30,(3,4))
print(a)
print(b)

[[11  1  8]
 [13  7 11]
 [ 7  3 11]
 [ 8 11  8]]
[[26 28 20 26]
 [21 29 21 23]
 [27 27 27 25]]


In [62]:
c=np.transpose(b)
b.resize(4,3) # resize doesn't return anything it directly changes the array but reshape() returns the changed array without changing original array
print(d)
print(a)
print(b)
a-b

[[26 28 20]
 [26 21 29]
 [21 23 27]
 [27 27 25]]
[[11  1  8]
 [13  7 11]
 [ 7  3 11]
 [ 8 11  8]]
[[26 28 20]
 [26 21 29]
 [21 23 27]
 [27 27 25]]


array([[-15, -27, -12],
       [-13, -14, -18],
       [-14, -20, -16],
       [-19, -16, -17]])